// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protobuff/store.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Number        int64                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Filename      *string                `protobuf:"bytes,5,opt,name=filename,proto3,oneof" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_protobuff_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_protobuff_store_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileChunk) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *FileChunk) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FileChunk) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

type StorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Node          int64                  `protobuf:"varint,3,opt,name=node,proto3" json:"node,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageResponse) Reset() {
	*x = StorageResponse{}
	mi := &file_protobuff_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResponse) ProtoMessage() {}

func (x *StorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResponse.ProtoReflect.Descriptor instead.
func (*StorageResponse) Descriptor() ([]byte, []int) {
	return file_protobuff_store_proto_rawDescGZIP(), []int{1}
}

func (x *StorageResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *StorageResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *StorageResponse) GetNode() int64 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *StorageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protobuff_store_proto protoreflect.FileDescriptor

const file_protobuff_store_proto_rawDesc = "" +
	"\n" +
	"\x15protobuff/store.proto\x12\astorage\"\x8d\x01\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x03R\x06number\x12\x16\n" +
	"\x06userId\x18\x04 \x01(\tR\x06userId\x12\x1f\n" +
	"\bfilename\x18\x05 \x01(\tH\x00R\bfilename\x88\x01\x01B\v\n" +
	"\t_filename\"p\n" +
	"\x0fStorageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04node\x18\x03 \x01(\x03R\x04node\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2I\n" +
	"\x0eStorageService\x127\n" +
	"\x05Store\x12\x12.storage.FileChunk\x1a\x18.storage.StorageResponse(\x01B\x12Z\x10/storage;storageb\x06proto3"

var (
	file_protobuff_store_proto_rawDescOnce sync.Once
	file_protobuff_store_proto_rawDescData []byte
)

func file_protobuff_store_proto_rawDescGZIP() []byte {
	file_protobuff_store_proto_rawDescOnce.Do(func() {
		file_protobuff_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff_store_proto_rawDesc), len(file_protobuff_store_proto_rawDesc)))
	})
	return file_protobuff_store_proto_rawDescData
}

var file_protobuff_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuff_store_proto_goTypes = []any{
	(*FileChunk)(nil),       // 0: storage.FileChunk
	(*StorageResponse)(nil), // 1: storage.StorageResponse
}
var file_protobuff_store_proto_depIdxs = []int32{
	0, // 0: storage.StorageService.Store:input_type -> storage.FileChunk
	1, // 1: storage.StorageService.Store:output_type -> storage.StorageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuff_store_proto_init() }
func file_protobuff_store_proto_init() {
	if File_protobuff_store_proto != nil {
		return
	}
	file_protobuff_store_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff_store_proto_rawDesc), len(file_protobuff_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_store_proto_goTypes,
		DependencyIndexes: file_protobuff_store_proto_depIdxs,
		MessageInfos:      file_protobuff_store_proto_msgTypes,
	}.Build()
	File_protobuff_store_proto = out.File
	file_protobuff_store_proto_goTypes = nil
	file_protobuff_store_proto_depIdxs = nil
}
