// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protobuff/uploader.proto

package uploader

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Number        int64                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	FileName      *string                `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3,oneof" json:"file_name,omitempty"`
	ContentType   *string                `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_protobuff_uploader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_uploader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_protobuff_uploader_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *FileChunk) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *FileChunk) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_protobuff_uploader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protobuff_uploader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_protobuff_uploader_proto_rawDescGZIP(), []int{1}
}

func (x *UploadStatus) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *UploadStatus) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protobuff_uploader_proto protoreflect.FileDescriptor

const file_protobuff_uploader_proto_rawDesc = "" +
	"\n" +
	"\x18protobuff/uploader.proto\x12\buploader\"\xa0\x01\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x03R\x06number\x12 \n" +
	"\tfile_name\x18\x03 \x01(\tH\x00R\bfileName\x88\x01\x01\x12&\n" +
	"\fcontent_type\x18\x04 \x01(\tH\x01R\vcontentType\x88\x01\x01B\f\n" +
	"\n" +
	"_file_nameB\x0f\n" +
	"\r_content_type\"Y\n" +
	"\fUploadStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2G\n" +
	"\fFileUploader\x127\n" +
	"\x06Upload\x12\x13.uploader.FileChunk\x1a\x16.uploader.UploadStatus(\x01B\x14Z\x12/uploader;uploaderb\x06proto3"

var (
	file_protobuff_uploader_proto_rawDescOnce sync.Once
	file_protobuff_uploader_proto_rawDescData []byte
)

func file_protobuff_uploader_proto_rawDescGZIP() []byte {
	file_protobuff_uploader_proto_rawDescOnce.Do(func() {
		file_protobuff_uploader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuff_uploader_proto_rawDesc), len(file_protobuff_uploader_proto_rawDesc)))
	})
	return file_protobuff_uploader_proto_rawDescData
}

var file_protobuff_uploader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuff_uploader_proto_goTypes = []any{
	(*FileChunk)(nil),    // 0: uploader.FileChunk
	(*UploadStatus)(nil), // 1: uploader.UploadStatus
}
var file_protobuff_uploader_proto_depIdxs = []int32{
	0, // 0: uploader.FileUploader.Upload:input_type -> uploader.FileChunk
	1, // 1: uploader.FileUploader.Upload:output_type -> uploader.UploadStatus
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuff_uploader_proto_init() }
func file_protobuff_uploader_proto_init() {
	if File_protobuff_uploader_proto != nil {
		return
	}
	file_protobuff_uploader_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuff_uploader_proto_rawDesc), len(file_protobuff_uploader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuff_uploader_proto_goTypes,
		DependencyIndexes: file_protobuff_uploader_proto_depIdxs,
		MessageInfos:      file_protobuff_uploader_proto_msgTypes,
	}.Build()
	File_protobuff_uploader_proto = out.File
	file_protobuff_uploader_proto_goTypes = nil
	file_protobuff_uploader_proto_depIdxs = nil
}
