// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const healthCheck = `-- name: HealthCheck :one
select (current_timestamp - pg_postmaster_start_time())::interval
`

func (q *Queries) HealthCheck(ctx context.Context) (pgtype.Interval, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var column_1 pgtype.Interval
	err := row.Scan(&column_1)
	return column_1, err
}
