
services:
    uploader-cache:
        image: redis:8.0.2-alpine
        container_name: uploadercache
        volumes:
            - rootredis:/root/redis
            - redisconf:/usr/local/etc/redis/redis.conf
            - cache-backup:/data
        restart: unless-stopped
        hostname: uploadercache
        environment:
            REDIS_HOST: ${REDIS_HOST}
            # REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_DATABASES: ${REDIS_DATABASES}
        ports:
            - "6379:6379"
volumes:
    cache-backup:
    rootredis:
    redisconf: